Algoritmo "LerMatriz"

Var
   Mat : Vetor [1..3,1..2] de Inteiro
   L, C : Inteiro
Inicio
   Para L<- 1 ate 3 faca
      Para C <- 1 ate 2 faca
         Escreva ("Digite o valor da posição: [", L, "," , C, "]: ")
         Leia (Mat [L,C])
      Fimpara
   Fimpara
   Para L<- 1 ate 3 faca
      Para C <- 1 ate 2 faca
         EScreva (Mat[L,C]:5)
      Fimpara
      EScreval ()
   Fimpara
Fimalgoritmo